/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logueo;

import java.io.*;
import javax.swing.JOptionPane;

public class Inicio_Sesion extends javax.swing.JFrame { 


    public String contraseñaR, contraseñaN;
    public String usuarioR, usuarioN;
    
    
    public Inicio_Sesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarior = new javax.swing.JLabel();
        contraseñar = new javax.swing.JLabel();
        usuariortxt = new javax.swing.JTextField();
        contraseñartxt = new javax.swing.JPasswordField();
        ingresobtn = new javax.swing.JButton();
        registrobtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarior.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuarior.setForeground(new java.awt.Color(255, 255, 255));
        usuarior.setText("Usuario: ");
        getContentPane().add(usuarior, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 80, 20));

        contraseñar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseñar.setForeground(new java.awt.Color(255, 255, 255));
        contraseñar.setText("Contraseña: ");
        getContentPane().add(contraseñar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        usuariortxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuariortxt.setText("usuario");
        usuariortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariortxtActionPerformed(evt);
            }
        });
        getContentPane().add(usuariortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, -1));

        contraseñartxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseñartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñartxtActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 180, -1));

        ingresobtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ingresobtn.setText("Ingresar");
        ingresobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresobtnMouseClicked(evt);
            }
        });
        ingresobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresobtnActionPerformed(evt);
            }
        });
        getContentPane().add(ingresobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        registrobtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registrobtn.setText("Registrar");
        registrobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrobtnMouseClicked(evt);
            }
        });
        registrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrobtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Iniciar Sesion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Empresa 1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/—Pngtree— red light flare ray_5265106.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariortxtActionPerformed

    private void contraseñartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñartxtActionPerformed

    private void ingresobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresobtnActionPerformed
        if(usuarioR.equals(usuarioN) && contraseñaR.equals(contraseñaN)){
        JOptionPane.showMessageDialog(null, "Sesion iniciada correctamente");
        }else{
        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos. Intente nuevmanete", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ingresobtnActionPerformed

    private void ingresobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresobtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresobtnMouseClicked

    private void registrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrobtnActionPerformed
 
    }//GEN-LAST:event_registrobtnActionPerformed

    private void registrobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrobtnMouseClicked
        Registro register = new Registro();
        register.setVisible(true);
    }//GEN-LAST:event_registrobtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseñar;
    private javax.swing.JPasswordField contraseñartxt;
    private javax.swing.JButton ingresobtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton registrobtn;
    private javax.swing.JLabel usuarior;
    private javax.swing.JTextField usuariortxt;
    // End of variables declaration//GEN-END:variables
}
