/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logueo;

import java.io.*;
import javax.swing.JOptionPane;
import java.util.*;

public class Registro extends javax.swing.JFrame {

    ArrayList<Registrarse> listaRegistrarse = new ArrayList();
    public String usuarioN;
    public String contraseñaN;
    public String nombre, apellidopa, apellidoma;
       
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombres = new javax.swing.JLabel();
        apellidop = new javax.swing.JLabel();
        apellidom = new javax.swing.JLabel();
        usuarion = new javax.swing.JLabel();
        contraseñan = new javax.swing.JLabel();
        confirmarcontran = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        apellidoptxt = new javax.swing.JTextField();
        apellidomtxt = new javax.swing.JTextField();
        usuariontxt = new javax.swing.JTextField();
        contraseñantxt = new javax.swing.JPasswordField();
        confirmarcontrantxt = new javax.swing.JPasswordField();
        confirmarregistrobtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nombres.setForeground(new java.awt.Color(255, 255, 255));
        nombres.setText("Nombre(s):  ");
        getContentPane().add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        apellidop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        apellidop.setForeground(new java.awt.Color(255, 255, 255));
        apellidop.setText("Apellido Paterno:");
        getContentPane().add(apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        apellidom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        apellidom.setForeground(new java.awt.Color(255, 255, 255));
        apellidom.setText("Apellido Materno: ");
        getContentPane().add(apellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        usuarion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuarion.setForeground(new java.awt.Color(255, 255, 255));
        usuarion.setText("Nombre de Usuario: ");
        getContentPane().add(usuarion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        contraseñan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseñan.setForeground(new java.awt.Color(255, 255, 255));
        contraseñan.setText("Contraseña: ");
        getContentPane().add(contraseñan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 20));

        confirmarcontran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmarcontran.setForeground(new java.awt.Color(255, 255, 255));
        confirmarcontran.setText("Confirmar Contraseña: ");
        getContentPane().add(confirmarcontran, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        nombretxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nombretxt.setText("nombre(s)    ");
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });
        getContentPane().add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 180, -1));

        apellidoptxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        apellidoptxt.setText("apellido paterno");
        getContentPane().add(apellidoptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, -1));

        apellidomtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        apellidomtxt.setText("apellido materno");
        getContentPane().add(apellidomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 180, -1));

        usuariontxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usuariontxt.setText("nombre de usuario");
        usuariontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariontxtActionPerformed(evt);
            }
        });
        getContentPane().add(usuariontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 180, -1));

        contraseñantxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        contraseñantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñantxtActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, -1));

        confirmarcontrantxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmarcontrantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarcontrantxtActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarcontrantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 180, -1));

        confirmarregistrobtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmarregistrobtn.setText("Registrarse");
        confirmarregistrobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarregistrobtnActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarregistrobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Registro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/—Pngtree— red light flare ray_5265106.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 680, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void confirmarregistrobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarregistrobtnActionPerformed
       if(usuarioN.equals(usuarioN) && contraseñaN.equals(contraseñaN)){
        JOptionPane.showMessageDialog(null, "Resgistro completado correctamente");
    }else{
         JOptionPane.showMessageDialog(null, "Algo salió mal en el registro.Intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_confirmarregistrobtnActionPerformed

    private void usuariontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariontxtActionPerformed
        
    }//GEN-LAST:event_usuariontxtActionPerformed

    private void contraseñantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñantxtActionPerformed
        
    }//GEN-LAST:event_contraseñantxtActionPerformed

    private void confirmarcontrantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarcontrantxtActionPerformed
       
    }//GEN-LAST:event_confirmarcontrantxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidom;
    private javax.swing.JTextField apellidomtxt;
    private javax.swing.JLabel apellidop;
    private javax.swing.JTextField apellidoptxt;
    private javax.swing.JLabel confirmarcontran;
    private javax.swing.JPasswordField confirmarcontrantxt;
    private javax.swing.JButton confirmarregistrobtn;
    private javax.swing.JLabel contraseñan;
    private javax.swing.JPasswordField contraseñantxt;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nombres;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JLabel usuarion;
    private javax.swing.JTextField usuariontxt;
    // End of variables declaration//GEN-END:variables
}
